In [2]:
import pandas as pd

In [3]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT))

In [4]:
df_atlas = pd.read_excel(
"C:/Users/olynthp/AppData/Local/Temp/MicrosoftEdgeDownloads/21e6dbe6-ee0b-4fd3-90fa-c0ba88ee9766/adh_radar_base_2012_2024.xlsx"
)

df_atlas.head()

,ANO,AGREGACAO,CODIGO,NOME,IDHM,IDHM_L,IDHM_E,IDHM_R,I_ESCOLARIDADE,I_FREQ_PROP,...,POP6A17,POP11A13,POP15A17,POP15M,POP18A20,POP18A24,POP18M,POP25M,POP65M,POPOCUP18M
0,2012,Brasil,NaN,Brasil,0.744,0.829,0.679,0.732,0.595,0.726,...,39808859,10304212,10609288,150994846,10076087,23924348,140385557,116461209,15249133,84277753
1,2013,Brasil,NaN,Brasil,0.752,0.833,0.692,0.737,0.606,0.739,...,39055262,9986737,10521249,153338252,10336072,24034903,142817003,118782100,15820311,86108710
2,2014,Brasil,NaN,Brasil,0.760,0.837,0.708,0.741,0.621,0.756,...,38765780,9687656,10446675,155356979,10224772,23840077,144910304,121070227,16425141,87308460
3,2015,Brasil,NaN,Brasil,0.762,0.839,0.717,0.736,0.632,0.764,...,38189476,9314134,10401307,157576293,10394554,23851445,147174986,123323541,17060247,87756538
4,2016,Brasil,NaN,Brasil,0.767,0.843,0.730,0.734,0.640,0.779,...,37694950,9288033,10375149,159692542,10242816,23779687,149317393,125537706,17728449,87110395

In [5]:
df_atlas.columns.tolist()

['ANO',
 'AGREGACAO',
 'CODIGO',
 'NOME',
 'IDHM',
 'IDHM_L',
 'IDHM_E',
 'IDHM_R',
 'I_ESCOLARIDADE',
 'I_FREQ_PROP',
 'IDHMAD',
 'IDHMAD_L',
 'IDHMAD_E',
 'IDHMAD_R',
 'ATK_ESPVIDA',
 'ATK_ANOSEST',
 'ATK_RDPC',
 'IDHMAD_PERDA',
 'IDHMAD_L_PERDA',
 'IDHMAD_E_PERDA',
 'IDHMAD_R_PERDA',
 'IDHMAD_COEF',
 'ESPVIDA',
 'MORT1',
 'T_ENV',
 'RAZDEP',
 'T_FREQ5A6',
 'T_FUND11A13',
 'T_FUND15A17',
 'T_MED18A20',
 'T_FUND18M',
 'ANOSEST',
 'T_ANALF15M',
 'T_ANALF18M',
 'T_ANALF25M',
 'T_FREQ6A14',
 'T_FREQ15A17',
 'T_FREQ18A24',
 'T_FUND18A24',
 'T_FUND25M',
 'T_MED25M',
 'T_SUPER25M',
 'T_ATRASO_2_BASICO',
 'T_ATRASO_2_FUND',
 'T_FLBAS',
 'T_FLFUND',
 'T_FLMED',
 'T_FLSUPER',
 'RDPC',
 'RDPCT',
 'RENOCUP',
 'PRENTRAB',
 'RDPC1',
 'RDPC2',
 'RDPC3',
 'RDPC4',
 'RDPC5',
 'RDPC10',
 'R1040',
 'R2040',
 'GINI',
 'THEIL',
 'PIND',
 'PMPOB',
 'PPOB',
 'RIND',
 'RMPOB',
 'RPOB',
 'POPTOT',
 'POP',
 'POPT',
 'POP5A6',
 'POP6A14',
 'POP6A17',
 'POP11A13',
 'POP15A17',
 'POP15M',
 'POP18A20',
 'POP18A24',
 'POP18M',
 'POP25M',
 'POP65M',
 'POPOCUP18M']

In [6]:
df_atlas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 702 entries, 0 to 701
Data columns (total 83 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ANO                702 non-null    int64
 1   AGREGACAO          702 non-null    object
 2   CODIGO             689 non-null    float64
 3   NOME               702 non-null    object
 4   IDHM               702 non-null    float64
 5   IDHM_L             702 non-null    float64
 6   IDHM_E             702 non-null    float64
 7   IDHM_R             702 non-null    float64
 8   I_ESCOLARIDADE     702 non-null    float64
 9   I_FREQ_PROP        702 non-null    float64
 10  IDHMAD             702 non-null    float64
 11  IDHMAD_L           702 non-null    float64
 12  IDHMAD_E           702 non-null    float64
 13  IDHMAD_R           702 non-null    float64
 14  ATK_ESPVIDA        702 non-null    float64
 15  ATK_ANOSEST        702 non-null    float64
 16  ATK_RDPC           702 non-null    float64
 17  IDHMAD_PERDA       702 non-null    float64
 18  IDHMAD_L_PERDA     702 non-null    float64
 19  IDHMAD_E_PERDA     702 non-null    float64
 20  IDHMAD_R_PERDA     702 non-null    float64
 21  IDHMAD_COEF        702 non-null    float64
 22  ESPVIDA            702 non-null    float64
 23  MORT1              702 non-null    float64
 24  T_ENV              702 non-null    float64
 25  RAZDEP             702 non-null    float64
 26  T_FREQ5A6          702 non-null    float64
 27  T_FUND11A13        702 non-null    float64
 28  T_FUND15A17        702 non-null    float64
 29  T_MED18A20         702 non-null    float64
 30  T_FUND18M          702 non-null    float64
 31  ANOSEST            702 non-null    float64
 32  T_ANALF15M         702 non-null    float64
 33  T_ANALF18M         702 non-null    float64
 34  T_ANALF25M         702 non-null    float64
 35  T_FREQ6A14         702 non-null    float64
 36  T_FREQ15A17        702 non-null    float64
 37  T_FREQ18A24        702 non-null    float64
 38  T_FUND18A24        702 non-null    float64
 39  T_FUND25M          702 non-null    float64
 40  T_MED25M           702 non-null    float64
 41  T_SUPER25M         702 non-null    float64
 42  T_ATRASO_2_BASICO  702 non-null    float64
 43  T_ATRASO_2_FUND    702 non-null    float64
 44  T_FLBAS            702 non-null    float64
 45  T_FLFUND           702 non-null    float64
 46  T_FLMED            702 non-null    float64
 47  T_FLSUPER          702 non-null    float64
 48  RDPC               702 non-null    float64
 49  RDPCT              702 non-null    float64
 50  RENOCUP            702 non-null    float64
 51  PRENTRAB           702 non-null    float64
 52  RDPC1              702 non-null    float64
 53  RDPC2              702 non-null    float64
 54  RDPC3              702 non-null    float64
 55  RDPC4              702 non-null    float64
 56  RDPC5              702 non-null    float64
 57  RDPC10             702 non-null    float64
 58  R1040              702 non-null    float64
 59  R2040              702 non-null    float64
 60  GINI               702 non-null    float64
 61  THEIL              702 non-null    float64
 62  PIND               702 non-null    float64
 63  PMPOB              702 non-null    float64
 64  PPOB               702 non-null    float64
 65  RIND               702 non-null    float64
 66  RMPOB              702 non-null    float64
 67  RPOB               702 non-null    float64
 68  POPTOT             702 non-null    int64
 69  POP                702 non-null    int64
 70  POPT               702 non-null    int64
 71  POP5A6             702 non-null    int64
 72  POP6A14            702 non-null    int64
 73  POP6A17            702 non-null    int64
 74  POP11A13           702 non-null    int64
 75  POP15A17           702 non-null    int64
 76  POP15M             702 non-null    int64
 77  POP18A20           702 non-null    int64
 78  POP18A24           702 non-null    int64
 79  POP18M             702 non-null    int64
 80  POP25M             702 non-null    int64
 81  POP65M             702 non-null    int64
 82  POPOCUP18M         702 non-null    int64
dtypes: float64(65), int64(16), object(2)
memory usage: 455.3+ KB

In [7]:
df_atlas['AGREGACAO'].value_counts()

AGREGACAO
Unidade da Federação              351
Região Metropolitana/Integrada    273
Grande Região                      65
Brasil                             13
Name: count, dtype: int64

In [8]:
df_atlas_uf = (
    df_atlas
    .query("AGREGACAO == 'Unidade da Federação'")
    .copy()
)

df_atlas_uf.shape

(351, 83)

In [9]:
atlas_uf = df_atlas_uf[
    [
        "ANO",
        'CODIGO', 
        'NOME', 
        'IDHM',
        'IDHM_E',
        'IDHM_R',
        'IDHM_L',
    ]
].copy()

In [10]:
atlas_uf.head(10)

     ANO  CODIGO       NOME   IDHM  IDHM_E  IDHM_R  IDHM_L
78  2012    11.0   Rondônia  0.708   0.625   0.692   0.820
79  2012    12.0       Acre  0.705   0.636   0.670   0.823
80  2012    13.0   Amazonas  0.706   0.627   0.683   0.820
81  2012    14.0    Roraima  0.761   0.742   0.717   0.827
82  2012    15.0       Pará  0.677   0.574   0.658   0.823
83  2012    16.0      Amapá  0.709   0.653   0.673   0.811
84  2012    17.0  Tocantins  0.721   0.665   0.674   0.835
85  2012    21.0   Maranhão  0.669   0.599   0.602   0.830
86  2012    22.0      Piauí  0.680   0.590   0.635   0.841
87  2012    23.0      Ceará  0.709   0.657   0.648   0.837

In [11]:
from src.silver.reader import read_silver_table

df_uf = read_silver_table("uf")

df_uf[["sigla_uf"]].drop_duplicates().sort_values("sigla_uf")

    sigla_uf
125       AC
8         AL
0         AM
3         AP
32        BA
7         CE
48        ES
20        GO
5         MA
35        MG
10        MS
6         MT
16        PA
1         PB
4         PE
11        PI
2         PR
44        RJ
33        RN
23        RO
18        RS
13        SC
17        SE
12        SP
38        TO

In [15]:
from src.silver.reader import read_layer_table

In [16]:
df = read_layer_table(
    layer="gold",
    table_name="comparativo_metas_resultados",
)

df.head()

,nivel_geografico,ano,id_municipio,id_municipio_nome,rede,taxa_alfabetizacao,ano_meta,meta_alfabetizacao,gap_para_meta,atingiu_meta,sigla_uf,sigla_uf_nome,_processed_ts,_layer,_table
0,brasil,2023,None,None,Pública,55.900002,2024,59.900002,4.00,False,None,None,2026-07-09 19:18:27.293082+00:00,gold,comparativo_metas_resultados
1,brasil,2023,None,None,Pública,55.900002,2025,63.770000,7.87,False,None,None,2026-07-09 19:18:27.293082+00:00,gold,comparativo_metas_resultados
2,brasil,2023,None,None,Pública,55.900002,2026,67.470001,11.57,False,None,None,2026-07-09 19:18:27.293082+00:00,gold,comparativo_metas_resultados
3,brasil,2023,None,None,Pública,55.900002,2027,70.970001,15.07,False,None,None,2026-07-09 19:18:27.293082+00:00,gold,comparativo_metas_resultados
4,brasil,2023,None,None,Pública,55.900002,2028,74.230003,18.33,False,None,None,2026-07-09 19:18:27.293082+00:00,gold,comparativo_metas_resultados

In [17]:
from src.gold.catalog import GOLD_CATALOG

GOLD_CATALOG.keys()

dict_keys(['indicador_alfabetizacao_municipio', 'comparativo_metas_resultados', 'evolucao_temporal_indicador', 'desempenho_alunos_municipio'])

In [18]:
df.columns.tolist()

['nivel_geografico',
 'ano',
 'id_municipio',
 'id_municipio_nome',
 'rede',
 'taxa_alfabetizacao',
 'ano_meta',
 'meta_alfabetizacao',
 'gap_para_meta',
 'atingiu_meta',
 'sigla_uf',
 'sigla_uf_nome',
 '_processed_ts',
 '_layer',
 '_table']